### PR TITLE
Modulesync

### PR DESCRIPTION
**Pull request by jyaworski**
This PR brings this under the control of https://github.com/puppet-community/modulesync_config

### CODE REVIEW

**Comment by jyaworski** [comment]
Slowly working on this. I suspect there will be some back and forth with the modulesync team on what constitutes a 'useful' cop to run, again.

I noticed that the files directory was exempt in rubocop. Was this a matter of convenience, or was there a functional reason behind it?

If it was convenience, I'll go through and edit the files.

**Comment by igalic** [comment]
*looks at files directory*

*cries*

**Comment by jyaworski** [comment]
Anyone have an idea about the files dir? If I don't get a response by tomorrow I'll just exclude it and move on.

**Comment by igalic** [comment]
@jyaworski for now, yes, :+1: on excluding
but, tbh, this stuff shouldn't be in files… see also: https://github.com/puppet-community/puppet-collectd/pull/358#issuecomment-150177836

**Comment by jyaworski** [comment]
This is now ready to merge.

**Comment by igalic** [comment]
thank you so much @jyaworski!

**Pull request merged**
