### PR TITLE
Pluginconf

### PR DESCRIPTION
**Pull request by CMartinUdden**
Hello!

This implements three main features

1. mcollective::userssl option to handle client keys or not (default to not do it as before)
2. Move all SSL functionality into the common "stage"
3. mcollective::pluginconf to facilitate easy plugin configuration

### CODE REVIEW

**Comment by igalic** [comment]
@CMartinUdden three general comments before i dive into this review:

* tests are failing :(
* please get rid of that merge-commit, by doing a proper [rebase](http://git-scm.com/book/en/Git-Branching-Rebasing)
* you may wanna add the email you used for these commits to your github settings so they can be associated.

**Comment by CMartinUdden** [comment]
Updated some tests and fixed the failing ones

**Comment by igalic** [comment]
@CMartinUdden I'm a bit confused as to why you closed this

**Comment by CMartinUdden** [comment]
New pull request ...

**Pull request closed without merging**
