### PR TITLE
yaml cronjob: change before / require of file refresh-mcollective-metadata

### PR DESCRIPTION
**Pull request by ffrank**
Cleaned up replacement for #174.

### CODE REVIEW

**Comment by nibalizer** [comment]
Unfortunately I broke this merge when I merged reid's change, but still LGTM.

**Comment by ffrank** [comment]
np, I'll keep rebasing.

Still have to scrutinize the tests before I merge, anyway.

**Comment by ffrank** [comment]
I just realized that GitHub's instructions of how to resolve the merge conflicts are **horrible**. Can we customize that somehow? cc @igalic

**Comment by ffrank** [comment]
OK the tests passed even with a typo in the spec file because setting `$server` to false will lead to the whole class missing, which does include the `cron`. So false positive. Everything is in order, though.

**Comment by ffrank** [comment]
Merged, pending release.

Thanks to @kronos-pbrideau for this contribution!

**Pull request merged**
