### PR TITLE
Fix strict_variables issue

### PR DESCRIPTION
**Pull request by mcanevet**

### CODE REVIEW

**Comment by mcanevet** [comment]
It looks like it is the right way to do it for now... https://github.com/puppetlabs/puppetlabs-concat/pull/270

**Comment by igalic** [comment]
apparently, this is the way we agreed to do things, until structured_facts is set by default: https://github.com/puppetlabs/puppetlabs-concat/pull/270

**Comment by igalic** [comment]
thanks @mcanevet!

**Comment by alexjfisher** [comment]
I'm not sure this is right. For me at least, /usr/local/libexec/mcollective/refresh-mcollective-metadata is broken.
```
head -n1 /usr/local/libexec/mcollective/refresh-mcollective-metadata
#!true
```

**Comment by alexjfisher** [comment]
It doesn't work in puppet 3.7.5 anyway.  Testing other versions now...
```
alex@alex-VirtualBox:~$ cat test.pp
notice ("puppetversion = ${::puppetversion}")
$var = defined('$is_pe') and $::is_pe ? {
  true    => 'is pe',
  default => 'is not pe',
}

notice ($var)
alex@alex-VirtualBox:~$ puppet apply test.pp
Notice: Scope(Class[main]): puppetversion = 3.7.5
Notice: Scope(Class[main]): true
Notice: Compiled catalog for alex-virtualbox.ordsvy.gov.uk in environment production in 0.01 seconds
Notice: Finished catalog run in 0.02 seconds
```

**Comment by alexjfisher** [comment]
Fixed in https://github.com/puppet-community/puppet-mcollective/pull/255

**Pull request merged**
